In [1]:
import pandas as pd

In [2]:
# DictionaryからDataFrameを作成 
data = { '名前': ['佐藤', '鈴木', '高橋'], '年齢': [25, 34, 29], '部署': ['営業', '開発', '人事'] }

In [3]:
df = pd.DataFrame(data) 
print(df)

   名前  年齢  部署
0  佐藤  25  営業
1  鈴木  34  開発
2  高橋  29  人事

In [4]:
df = pd.read_csv('golf_play.csv', encoding="utf8") 
df.head()

    Outlook Temperature Humidity  Windy Play
0     sunny         hot     high  False   no
1     sunny         hot     high   True   no
2  overcast         hot     high  False  yes
3     rainy        mild     high  False  yes
4     rainy        cool   normal  False  yes

In [5]:
df.tail()

     Outlook Temperature Humidity  Windy Play
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [6]:
# ラベル指定：loc による指定列名や条件式で抽出。
# 天気予報Outlookが"rainy"である行のPlayの列を選択 
df.loc[df['Outlook'] == 'rainy', 'Play']

3     yes
4     yes
5      no
9     yes
13     no
Name: Play, dtype: object

In [7]:
# インデックス指定：iloc による指定行・列番号（数値）で指定。
# 0〜4行目、0〜2列目を抽出 
df.iloc[0:5, 0:2]

    Outlook Temperature
0     sunny         hot
1     sunny         hot
2  overcast         hot
3     rainy        mild
4     rainy        cool

In [8]:
# 複数条件：論理演算フィルタAND(&)やOR（|）で指定
# Outlookがsunnyで かつ Humidityがnormalである行 
df[(df['Outlook']=='sunny') & (df['Humidity']=='normal')]

   Outlook Temperature Humidity  Windy Play
8    sunny        cool   normal  False  yes
10   sunny        mild   normal   True  yes